version: "3.8"
services:
  postgres:
    image: postgres:17.0
    environment:
      POSTGRES_DB: "${PG_DB}"
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
    ports:
      - 5432:5432
    volumes:
      - "./database/postgres-data:/var/lib/postgresql/data:rw"
  elasticmq:
    image: softwaremill/elasticmq-native
    ports:
      - 9324:9324
      - 9325:9325
    volumes:
      - ./elasticmq.conf:/opt/elasticmq.conf
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio:/data
    command: server /data --console-address ":9001"

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - prometheus:/prometheus
      - ./prometheus/development.yml:/etc/prometheus/prometheus.yml
  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - alertmanager:/alertmanager
      - ./alertmanager/development.yml:/etc/alertmanager/alertmanager.yml

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/etc/dashboards
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini

  postgres-test:
    image: postgres:17.0
    environment:
      POSTGRES_DB: "${PG_DB_TEST}"
      POSTGRES_USER: "${PG_USER_TEST}"
      POSTGRES_PASSWORD: "${PG_PASSWORD_TEST}"
    ports:
      - 5433:5432
volumes:
  postgres:
  minio:
  prometheus:
  alertmanager:
  grafana:
